%% This script cleans the AP4 model's workspace for only relevant outputs
clearvars -except AP4_County_List AP4_EGU_List Emissions_2017_NEI ...
    SR_Matrices_Ground SR_Matrices_Point_EGU SR_Matrices_Point_Non_EGU ...
    MC_Ground_NH3 MC_Non_EGU_Point_NH3 MC_EGU_Point_NH3 ...
    MC_Ground_NOx MC_Non_EGU_Point_NOx MC_EGU_Point_NOx ...
    MC_Ground_PMP MC_Non_EGU_Point_PMP MC_EGU_Point_PMP ...
    MC_Ground_SO2 MC_Non_EGU_Point_SO2 MC_EGU_Point_SO2 ...
    MC_Ground_VOC MC_Non_EGU_Point_VOC MC_EGU_Point_VOC ...
    Results_MC

%% end of script.