%% This script cleans the AP4 model's workspace for only relevant outputs
clearvars -except AP4_County_List AP4_EGU_List dr dr_infant ... 
Emissions_2017_NEI MR_Data Population_Data ...
MD_EGU_Point MD_Ground MD_Non_EGU_Point MD_Summary_Matrix ...
SR_Matrices_Ground SR_Matrices_Point_EGU SR_Matrices_Point_Non_EGU ...
usd_year wtp wtp_year

%% end of script.


