% tractOutputF2.m
% Writes to CSV file the marginal damages per short ton of source pollutant
function tractOutputF2(cfips, b, p, bin, pollutant, data_md, mt_to_st)
    dlmwrite(['AP4_Tract_Outputs/AP4_Tract_Counties/AP4_Tract_' ...
        num2str(cfips,'%05.f') '/AP4_Tract_' pollutant '_' ...
        num2str(cfips,'%05.f') '/AP4_Tract_' bin '_' pollutant ...
        '_MM_' num2str(cfips,'%05.f') '.csv'], ...
        data_md{b,p}*mt_to_st, 'precision', 12)
endfunction