function tractOutputF4(ft, p, pollutant, data_md, mt_to_st)
    dlmwrite(['AP4_Tract_Outputs/AP4_Tract_EGUs/AP4_Tract_' ...
        ft '/AP4_Tract_' pollutant '_' ft ...
        '/AP4_Tract_EGU_' pollutant '_MM_' ft '.csv'], ...
        data_md{1,p}*mt_to_st, 'precision', 12)
endfunction